/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as PortfolioProjectSlugRouteImport } from './routes/portfolio/$projectSlug'
import { Route as PortfolioCommercialRetailRouteImport } from './routes/portfolio/commercial-retail'
import { Route as PortfolioCustomHomesRouteImport } from './routes/portfolio/custom-homes'
import { Route as PortfolioDaycareRecreationRouteImport } from './routes/portfolio/daycare-recreation'
import { Route as PortfolioHealthcareRouteImport } from './routes/portfolio/healthcare'
import { Route as PortfolioIndustrialRouteImport } from './routes/portfolio/industrial'
import { Route as PortfolioInstitutionalRouteImport } from './routes/portfolio/institutional'
import { Route as PortfolioLaboratoryRouteImport } from './routes/portfolio/laboratory'
import { Route as PortfolioLavaGrilleMarkhamRouteImport } from './routes/portfolio/lava-grille-markham'
import { Route as PortfolioMidriseResidentialRouteImport } from './routes/portfolio/midrise-residential'
import { Route as PortfolioModularHouseRouteImport } from './routes/portfolio/modular-house'
import { Route as PortfolioMultiplexInfillRouteImport } from './routes/portfolio/multiplex-infill'
import { Route as PortfolioOfficeRouteImport } from './routes/portfolio/office'
import { Route as PortfolioOfficesRouteImport } from './routes/portfolio/offices'
import { Route as PortfolioPremiseIsolationRouteImport } from './routes/portfolio/premise-isolation'
import { Route as PortfolioRestaurantsRouteImport } from './routes/portfolio/restaurants'
import { Route as PortfolioSportsGymRouteImport } from './routes/portfolio/sports-gym'
import { Route as PortfolioTownhouseRouteImport } from './routes/portfolio/townhouse'
import { Route as PortfolioWorshipRouteImport } from './routes/portfolio/worship'
import { Route as PortfolioSectorSectorIdRouteImport } from './routes/portfolio/sector/$sectorId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioProjectSlugRoute = PortfolioProjectSlugRouteImport.update({
  id: '/portfolio/$projectSlug',
  path: '/portfolio/$projectSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioCommercialRetailRoute =
  PortfolioCommercialRetailRouteImport.update({
    id: '/portfolio/commercial-retail',
    path: '/portfolio/commercial-retail',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioCustomHomesRoute = PortfolioCustomHomesRouteImport.update({
  id: '/portfolio/custom-homes',
  path: '/portfolio/custom-homes',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioDaycareRecreationRoute =
  PortfolioDaycareRecreationRouteImport.update({
    id: '/portfolio/daycare-recreation',
    path: '/portfolio/daycare-recreation',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioHealthcareRoute = PortfolioHealthcareRouteImport.update({
  id: '/portfolio/healthcare',
  path: '/portfolio/healthcare',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndustrialRoute = PortfolioIndustrialRouteImport.update({
  id: '/portfolio/industrial',
  path: '/portfolio/industrial',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioInstitutionalRoute = PortfolioInstitutionalRouteImport.update({
  id: '/portfolio/institutional',
  path: '/portfolio/institutional',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioLaboratoryRoute = PortfolioLaboratoryRouteImport.update({
  id: '/portfolio/laboratory',
  path: '/portfolio/laboratory',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioLavaGrilleMarkhamRoute =
  PortfolioLavaGrilleMarkhamRouteImport.update({
    id: '/portfolio/lava-grille-markham',
    path: '/portfolio/lava-grille-markham',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioMidriseResidentialRoute =
  PortfolioMidriseResidentialRouteImport.update({
    id: '/portfolio/midrise-residential',
    path: '/portfolio/midrise-residential',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioModularHouseRoute = PortfolioModularHouseRouteImport.update({
  id: '/portfolio/modular-house',
  path: '/portfolio/modular-house',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioMultiplexInfillRoute =
  PortfolioMultiplexInfillRouteImport.update({
    id: '/portfolio/multiplex-infill',
    path: '/portfolio/multiplex-infill',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioOfficeRoute = PortfolioOfficeRouteImport.update({
  id: '/portfolio/office',
  path: '/portfolio/office',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioOfficesRoute = PortfolioOfficesRouteImport.update({
  id: '/portfolio/offices',
  path: '/portfolio/offices',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioPremiseIsolationRoute =
  PortfolioPremiseIsolationRouteImport.update({
    id: '/portfolio/premise-isolation',
    path: '/portfolio/premise-isolation',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioRestaurantsRoute = PortfolioRestaurantsRouteImport.update({
  id: '/portfolio/restaurants',
  path: '/portfolio/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSportsGymRoute = PortfolioSportsGymRouteImport.update({
  id: '/portfolio/sports-gym',
  path: '/portfolio/sports-gym',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioTownhouseRoute = PortfolioTownhouseRouteImport.update({
  id: '/portfolio/townhouse',
  path: '/portfolio/townhouse',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioWorshipRoute = PortfolioWorshipRouteImport.update({
  id: '/portfolio/worship',
  path: '/portfolio/worship',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSectorSectorIdRoute = PortfolioSectorSectorIdRouteImport.update({
  id: '/portfolio/sector/$sectorId',
  path: '/portfolio/sector/$sectorId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/portfolio/$projectSlug': typeof PortfolioProjectSlugRoute
  '/portfolio/commercial-retail': typeof PortfolioCommercialRetailRoute
  '/portfolio/custom-homes': typeof PortfolioCustomHomesRoute
  '/portfolio/daycare-recreation': typeof PortfolioDaycareRecreationRoute
  '/portfolio/healthcare': typeof PortfolioHealthcareRoute
  '/portfolio/industrial': typeof PortfolioIndustrialRoute
  '/portfolio/institutional': typeof PortfolioInstitutionalRoute
  '/portfolio/laboratory': typeof PortfolioLaboratoryRoute
  '/portfolio/lava-grille-markham': typeof PortfolioLavaGrilleMarkhamRoute
  '/portfolio/midrise-residential': typeof PortfolioMidriseResidentialRoute
  '/portfolio/modular-house': typeof PortfolioModularHouseRoute
  '/portfolio/multiplex-infill': typeof PortfolioMultiplexInfillRoute
  '/portfolio/office': typeof PortfolioOfficeRoute
  '/portfolio/offices': typeof PortfolioOfficesRoute
  '/portfolio/premise-isolation': typeof PortfolioPremiseIsolationRoute
  '/portfolio/restaurants': typeof PortfolioRestaurantsRoute
  '/portfolio/sports-gym': typeof PortfolioSportsGymRoute
  '/portfolio/townhouse': typeof PortfolioTownhouseRoute
  '/portfolio/worship': typeof PortfolioWorshipRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/portfolio/sector/$sectorId': typeof PortfolioSectorSectorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/portfolio/$projectSlug': typeof PortfolioProjectSlugRoute
  '/portfolio/commercial-retail': typeof PortfolioCommercialRetailRoute
  '/portfolio/custom-homes': typeof PortfolioCustomHomesRoute
  '/portfolio/daycare-recreation': typeof PortfolioDaycareRecreationRoute
  '/portfolio/healthcare': typeof PortfolioHealthcareRoute
  '/portfolio/industrial': typeof PortfolioIndustrialRoute
  '/portfolio/institutional': typeof PortfolioInstitutionalRoute
  '/portfolio/laboratory': typeof PortfolioLaboratoryRoute
  '/portfolio/lava-grille-markham': typeof PortfolioLavaGrilleMarkhamRoute
  '/portfolio/midrise-residential': typeof PortfolioMidriseResidentialRoute
  '/portfolio/modular-house': typeof PortfolioModularHouseRoute
  '/portfolio/multiplex-infill': typeof PortfolioMultiplexInfillRoute
  '/portfolio/office': typeof PortfolioOfficeRoute
  '/portfolio/offices': typeof PortfolioOfficesRoute
  '/portfolio/premise-isolation': typeof PortfolioPremiseIsolationRoute
  '/portfolio/restaurants': typeof PortfolioRestaurantsRoute
  '/portfolio/sports-gym': typeof PortfolioSportsGymRoute
  '/portfolio/townhouse': typeof PortfolioTownhouseRoute
  '/portfolio/worship': typeof PortfolioWorshipRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/portfolio/sector/$sectorId': typeof PortfolioSectorSectorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/portfolio/$projectSlug': typeof PortfolioProjectSlugRoute
  '/portfolio/commercial-retail': typeof PortfolioCommercialRetailRoute
  '/portfolio/custom-homes': typeof PortfolioCustomHomesRoute
  '/portfolio/daycare-recreation': typeof PortfolioDaycareRecreationRoute
  '/portfolio/healthcare': typeof PortfolioHealthcareRoute
  '/portfolio/industrial': typeof PortfolioIndustrialRoute
  '/portfolio/institutional': typeof PortfolioInstitutionalRoute
  '/portfolio/laboratory': typeof PortfolioLaboratoryRoute
  '/portfolio/lava-grille-markham': typeof PortfolioLavaGrilleMarkhamRoute
  '/portfolio/midrise-residential': typeof PortfolioMidriseResidentialRoute
  '/portfolio/modular-house': typeof PortfolioModularHouseRoute
  '/portfolio/multiplex-infill': typeof PortfolioMultiplexInfillRoute
  '/portfolio/office': typeof PortfolioOfficeRoute
  '/portfolio/offices': typeof PortfolioOfficesRoute
  '/portfolio/premise-isolation': typeof PortfolioPremiseIsolationRoute
  '/portfolio/restaurants': typeof PortfolioRestaurantsRoute
  '/portfolio/sports-gym': typeof PortfolioSportsGymRoute
  '/portfolio/townhouse': typeof PortfolioTownhouseRoute
  '/portfolio/worship': typeof PortfolioWorshipRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/portfolio/sector/$sectorId': typeof PortfolioSectorSectorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/services'
    | '/portfolio/$projectSlug'
    | '/portfolio/commercial-retail'
    | '/portfolio/custom-homes'
    | '/portfolio/daycare-recreation'
    | '/portfolio/healthcare'
    | '/portfolio/industrial'
    | '/portfolio/institutional'
    | '/portfolio/laboratory'
    | '/portfolio/lava-grille-markham'
    | '/portfolio/midrise-residential'
    | '/portfolio/modular-house'
    | '/portfolio/multiplex-infill'
    | '/portfolio/office'
    | '/portfolio/offices'
    | '/portfolio/premise-isolation'
    | '/portfolio/restaurants'
    | '/portfolio/sports-gym'
    | '/portfolio/townhouse'
    | '/portfolio/worship'
    | '/portfolio/'
    | '/portfolio/sector/$sectorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/services'
    | '/portfolio/$projectSlug'
    | '/portfolio/commercial-retail'
    | '/portfolio/custom-homes'
    | '/portfolio/daycare-recreation'
    | '/portfolio/healthcare'
    | '/portfolio/industrial'
    | '/portfolio/institutional'
    | '/portfolio/laboratory'
    | '/portfolio/lava-grille-markham'
    | '/portfolio/midrise-residential'
    | '/portfolio/modular-house'
    | '/portfolio/multiplex-infill'
    | '/portfolio/office'
    | '/portfolio/offices'
    | '/portfolio/premise-isolation'
    | '/portfolio/restaurants'
    | '/portfolio/sports-gym'
    | '/portfolio/townhouse'
    | '/portfolio/worship'
    | '/portfolio'
    | '/portfolio/sector/$sectorId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/services'
    | '/portfolio/$projectSlug'
    | '/portfolio/commercial-retail'
    | '/portfolio/custom-homes'
    | '/portfolio/daycare-recreation'
    | '/portfolio/healthcare'
    | '/portfolio/industrial'
    | '/portfolio/institutional'
    | '/portfolio/laboratory'
    | '/portfolio/lava-grille-markham'
    | '/portfolio/midrise-residential'
    | '/portfolio/modular-house'
    | '/portfolio/multiplex-infill'
    | '/portfolio/office'
    | '/portfolio/offices'
    | '/portfolio/premise-isolation'
    | '/portfolio/restaurants'
    | '/portfolio/sports-gym'
    | '/portfolio/townhouse'
    | '/portfolio/worship'
    | '/portfolio/'
    | '/portfolio/sector/$sectorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  PortfolioProjectSlugRoute: typeof PortfolioProjectSlugRoute
  PortfolioCommercialRetailRoute: typeof PortfolioCommercialRetailRoute
  PortfolioCustomHomesRoute: typeof PortfolioCustomHomesRoute
  PortfolioDaycareRecreationRoute: typeof PortfolioDaycareRecreationRoute
  PortfolioHealthcareRoute: typeof PortfolioHealthcareRoute
  PortfolioIndustrialRoute: typeof PortfolioIndustrialRoute
  PortfolioInstitutionalRoute: typeof PortfolioInstitutionalRoute
  PortfolioLaboratoryRoute: typeof PortfolioLaboratoryRoute
  PortfolioLavaGrilleMarkhamRoute: typeof PortfolioLavaGrilleMarkhamRoute
  PortfolioMidriseResidentialRoute: typeof PortfolioMidriseResidentialRoute
  PortfolioModularHouseRoute: typeof PortfolioModularHouseRoute
  PortfolioMultiplexInfillRoute: typeof PortfolioMultiplexInfillRoute
  PortfolioOfficeRoute: typeof PortfolioOfficeRoute
  PortfolioOfficesRoute: typeof PortfolioOfficesRoute
  PortfolioPremiseIsolationRoute: typeof PortfolioPremiseIsolationRoute
  PortfolioRestaurantsRoute: typeof PortfolioRestaurantsRoute
  PortfolioSportsGymRoute: typeof PortfolioSportsGymRoute
  PortfolioTownhouseRoute: typeof PortfolioTownhouseRoute
  PortfolioWorshipRoute: typeof PortfolioWorshipRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  PortfolioSectorSectorIdRoute: typeof PortfolioSectorSectorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$projectSlug': {
      id: '/portfolio/$projectSlug'
      path: '/portfolio/$projectSlug'
      fullPath: '/portfolio/$projectSlug'
      preLoaderRoute: typeof PortfolioProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/commercial-retail': {
      id: '/portfolio/commercial-retail'
      path: '/portfolio/commercial-retail'
      fullPath: '/portfolio/commercial-retail'
      preLoaderRoute: typeof PortfolioCommercialRetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/custom-homes': {
      id: '/portfolio/custom-homes'
      path: '/portfolio/custom-homes'
      fullPath: '/portfolio/custom-homes'
      preLoaderRoute: typeof PortfolioCustomHomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/daycare-recreation': {
      id: '/portfolio/daycare-recreation'
      path: '/portfolio/daycare-recreation'
      fullPath: '/portfolio/daycare-recreation'
      preLoaderRoute: typeof PortfolioDaycareRecreationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/healthcare': {
      id: '/portfolio/healthcare'
      path: '/portfolio/healthcare'
      fullPath: '/portfolio/healthcare'
      preLoaderRoute: typeof PortfolioHealthcareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/industrial': {
      id: '/portfolio/industrial'
      path: '/portfolio/industrial'
      fullPath: '/portfolio/industrial'
      preLoaderRoute: typeof PortfolioIndustrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/institutional': {
      id: '/portfolio/institutional'
      path: '/portfolio/institutional'
      fullPath: '/portfolio/institutional'
      preLoaderRoute: typeof PortfolioInstitutionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/laboratory': {
      id: '/portfolio/laboratory'
      path: '/portfolio/laboratory'
      fullPath: '/portfolio/laboratory'
      preLoaderRoute: typeof PortfolioLaboratoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/lava-grille-markham': {
      id: '/portfolio/lava-grille-markham'
      path: '/portfolio/lava-grille-markham'
      fullPath: '/portfolio/lava-grille-markham'
      preLoaderRoute: typeof PortfolioLavaGrilleMarkhamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/midrise-residential': {
      id: '/portfolio/midrise-residential'
      path: '/portfolio/midrise-residential'
      fullPath: '/portfolio/midrise-residential'
      preLoaderRoute: typeof PortfolioMidriseResidentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/modular-house': {
      id: '/portfolio/modular-house'
      path: '/portfolio/modular-house'
      fullPath: '/portfolio/modular-house'
      preLoaderRoute: typeof PortfolioModularHouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/multiplex-infill': {
      id: '/portfolio/multiplex-infill'
      path: '/portfolio/multiplex-infill'
      fullPath: '/portfolio/multiplex-infill'
      preLoaderRoute: typeof PortfolioMultiplexInfillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/office': {
      id: '/portfolio/office'
      path: '/portfolio/office'
      fullPath: '/portfolio/office'
      preLoaderRoute: typeof PortfolioOfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/offices': {
      id: '/portfolio/offices'
      path: '/portfolio/offices'
      fullPath: '/portfolio/offices'
      preLoaderRoute: typeof PortfolioOfficesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/premise-isolation': {
      id: '/portfolio/premise-isolation'
      path: '/portfolio/premise-isolation'
      fullPath: '/portfolio/premise-isolation'
      preLoaderRoute: typeof PortfolioPremiseIsolationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/restaurants': {
      id: '/portfolio/restaurants'
      path: '/portfolio/restaurants'
      fullPath: '/portfolio/restaurants'
      preLoaderRoute: typeof PortfolioRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/sports-gym': {
      id: '/portfolio/sports-gym'
      path: '/portfolio/sports-gym'
      fullPath: '/portfolio/sports-gym'
      preLoaderRoute: typeof PortfolioSportsGymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/townhouse': {
      id: '/portfolio/townhouse'
      path: '/portfolio/townhouse'
      fullPath: '/portfolio/townhouse'
      preLoaderRoute: typeof PortfolioTownhouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/worship': {
      id: '/portfolio/worship'
      path: '/portfolio/worship'
      fullPath: '/portfolio/worship'
      preLoaderRoute: typeof PortfolioWorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/sector/$sectorId': {
      id: '/portfolio/sector/$sectorId'
      path: '/portfolio/sector/$sectorId'
      fullPath: '/portfolio/sector/$sectorId'
      preLoaderRoute: typeof PortfolioSectorSectorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  PortfolioProjectSlugRoute: PortfolioProjectSlugRoute,
  PortfolioCommercialRetailRoute: PortfolioCommercialRetailRoute,
  PortfolioCustomHomesRoute: PortfolioCustomHomesRoute,
  PortfolioDaycareRecreationRoute: PortfolioDaycareRecreationRoute,
  PortfolioHealthcareRoute: PortfolioHealthcareRoute,
  PortfolioIndustrialRoute: PortfolioIndustrialRoute,
  PortfolioInstitutionalRoute: PortfolioInstitutionalRoute,
  PortfolioLaboratoryRoute: PortfolioLaboratoryRoute,
  PortfolioLavaGrilleMarkhamRoute: PortfolioLavaGrilleMarkhamRoute,
  PortfolioMidriseResidentialRoute: PortfolioMidriseResidentialRoute,
  PortfolioModularHouseRoute: PortfolioModularHouseRoute,
  PortfolioMultiplexInfillRoute: PortfolioMultiplexInfillRoute,
  PortfolioOfficeRoute: PortfolioOfficeRoute,
  PortfolioOfficesRoute: PortfolioOfficesRoute,
  PortfolioPremiseIsolationRoute: PortfolioPremiseIsolationRoute,
  PortfolioRestaurantsRoute: PortfolioRestaurantsRoute,
  PortfolioSportsGymRoute: PortfolioSportsGymRoute,
  PortfolioTownhouseRoute: PortfolioTownhouseRoute,
  PortfolioWorshipRoute: PortfolioWorshipRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  PortfolioSectorSectorIdRoute: PortfolioSectorSectorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
